# Welcome to Jekyll!
#
# Site settings
title: thbe's project page
email: project@bendler-net.de
description: >-
  This site contain some of my project repositories with code I've wrote over the
  last years.
baseurl: ""
url: "https://thbe.github.io"
twitter_username: thbe007
github_username:  thbe
permalink: /:year-:month-:day-:title

# Gitpages
show_downloads: false

# Build settings
markdown: kramdown
theme: jekyll-theme-tactile
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-redirect-from
